apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-ds
  namespace: kube-system
  labels:
    name: fluentd-logging
    function: logging

spec:
  selector:
    matchLabels:
      name: fluentd-pod
  template:
    metadata:
      labels:
        name: fluentd-pod
    spec:
      tolerations:
        # this toleration is to have the daemonset runnable on master nodes
        # remove it if your masters can't run pods
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      serviceAccount: fluentd
      serviceAccountName: fluentd
      containers:
        - image: quay.io/fluentd_elasticsearch/fluentd:v3.0.1
          name: fluentd
          resources:
            requests:
              cpu: 0.5
              memory: 200Mi
            limits:
              memory: 200Mi
          volumeMounts:
            - mountPath: /etc/fluent
              name: config-file
            - mountPath: /var/log
              name: var-log
            - mountPath: /var/lib/docker/containers
              name: varlibdockercontainers
              readOnly: True
          env:
           - name:  FLUENT_ELASTICSEARCH_HOST
             value: "elasticsearch.logging"
           - name:  FLUENT_ELASTICSEARCH_PORT
             value: "9200"
           - name: FLUENT_ELASTICSEARCH_SCHEME
             value: "http"
           - name: FLUENT_UID
             value: "0"
      terminationGracePeriodSeconds: 30
      volumes:
        - name: var-log
          hostPath:
            path: /D/fluentd/log'
        - name: varlibdockercontainers
          hostPath:
            path: /D/fluentd/lib/docker/containers'
        - name: config-file
          configMap:
            name: fluentd-configmap
            items:
              - key: fluent.conf
                path: fluent.conf


